version: 2
jobs:
  build:
    working_directory: ~/wp-cli/package-tests
    parallelism: 1
    docker:
    - image: circleci/php:7.1
    - image: circleci/mysql:5.6
    steps:
    - checkout
    - run: |
        sudo sh -c "printf '\ndeb http://ftp.us.debian.org/debian sid main\n' >> /etc/apt/sources.list"
        sudo apt-get update
        sudo docker-php-ext-install mysqli
        sudo apt-get install mysql-client-5.7
    - run: |
        echo -e "memory_limit = 1024M" | sudo tee /usr/local/etc/php/php.ini > /dev/null
    - run: |
        composer require wp-cli/wp-cli:dev-master
        composer install
        bash bin/install-package-tests.sh
    - run: |
        echo 'export PATH=$HOME/wp-cli/package-tests/vendor/bin:$PATH' >> $BASH_ENV
        source $BASH_ENV
    - run: |
        composer validate
        WP_VERSION=latest bash bin/test.sh
        rm -rf '/tmp/wp-cli-test core-download-cache'
        WP_VERSION=trunk bash bin/test.sh
